out_dir: results_modnet_pub
metric_best: modularity
device: cpu # gpu works but does not provide advantage on my setup
dataset:
  format: modnet  # instructs GG to use the proper loader for modnet graphs
  interpretation: single
  name: pregen-modnet-graph  # does not matter here
  dir: associative_n=400_k=5  # from where to load pre-generated graphs from
  task: node
  task_type: community
  num_communities: 5  # see parameter k in dataset.dir
  transductive: True  # can only generate embeddings for nodes seen during training phase
  split: [1.0] # only trivial split
  augment_feature_dims: [1]
  augment_feature_repr: original
train:
  mode: train_with_adj  
  eval_period: 100
  ckpt_period: 100
model:
  type: gnn
  loss_fun: soft_modularity_bipartite
  collapse_lam: 0.0
gnn:
  layers_pre_mp: 0  # like in original modnet publication
  layers_mp: 2  # like in original modnet publication
  layers_post_mp: 1  # like in original modnet publication
  layer_type: generalconv
  stage_type: stack
  batchnorm: False
  act: prelu
  dropout: 0.0 # like in modnet
  agg: add  # ?? what are the options?
  normalize_adj: False # ??
optim:
  optimizer: adam # ??
  base_lr: 0.1  # like in modnet
  max_epoch: 300  # modnet: 150
