out_dir: results
metric_best: modularity
dataset:
  format: SBM_gen_rpt
  interpretation: bipartite
  name: kHSBM
  dir: easy_4
  task: node
  task_type: community
  num_communities: 4
  transductive: True  # can only generate embeddings for nodes seen during training phase
  split: [1.0] # only trivial split
  # use default values for SBM generation for now
train:
  mode: run_alg
model:
  loss_fun: soft_modularity_bipartite

# any other params should not matter